openapi: 3.0.3
info:
  title: pagoPA Wallet API
  version: "0.1"
  description: |-
    Wallet
  termsOfService: https://pagopa.it/terms/
paths:
  /wallets:
    post:
      tags:
        - wallets
      summary: Create a new wallet
      description: Creates a new wallet
      operationId: createWallet
      requestBody:
        description: |-
          Request body containing the information to create a new wallet.
          A wallet is a collection of payment instruments that _may_ be associated to a user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWalletRequest'
        required: true
      responses:
        '200':
          description: Wallet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWalletResponse'
        '405':
          description: Invalid input
  /wallets/{walletId}:
    get:
      tags:
        - wallets
      summary: Get wallet by id
      description: Returns a single wallet
      operationId: getWalletById
      parameters:
        - name: walletId
          in: path
          description: Id of the wallet to return
          required: true
          schema:
            $ref: "#/components/schemas/WalletId"
      responses:
        '200':
          description: Wallet retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletInfo'
        '400':
          description: Malformed wallet id supplied
        '404':
          description: Wallet corresponding to the supplied wallet id not found
components:
  schemas:
    WalletId:
      type: string
      format: uuid
    WalletInfo:
      type: object
      properties:
        walletId:
          $ref: "#/components/schemas/WalletId"
      required:
        - walletId
    CreateWalletRequest:
      type: object
    CreateWalletResponse:
      type: object
      properties:
        walletId:
          $ref: "#/components/schemas/WalletId"
      required:
        - walletId
