openapi: 3.0.3
info:
  title: pagoPA Wallet API
  version: "0.1"
  description: |-
    Wallet
  termsOfService: https://pagopa.it/terms/
externalDocs:
  description: SANP – Specifiche Attuative del Nodo dei Pagamenti
  url: https://docs.pagopa.it/sanp/specifiche-attuative-del-nodo-dei-pagamenti-spc/
paths:
  /wallets:
    post:
      tags:
        - wallets
      summary: Create a new wallet
      description: Creates a new wallet
      operationId: createWallet
      requestBody:
        description: |-
          Request body containing the information to create a new wallet.
          A wallet is a collection of payment instruments that _may_ be associated to a user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWalletRequest'
        required: true
      responses:
        '200':
          description: Wallet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWalletResponse'
        '405':
          description: Invalid input
  /wallets/{walletId}:
    put:
      tags:
        - wallets
      summary: Update an existing wallet
      description: Updates an existing wallet by id
      operationId: updateWallet
      parameters:
        - name: walletId
          in: path
          description: Id of the wallet that is about to be updated
          required: true
          schema:
            $ref: "#/components/schemas/WalletId"
      requestBody:
        description: Update request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWalletRequest'
        required: true
      responses:
        '200':
          description: Wallet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateWalletResponse'
        '400':
          description: Malformed wallet id supplied
        '404':
          description: Wallet corresponding to the supplied wallet id not found
    get:
      tags:
        - wallets
      summary: Find wallet by id
      description: Returns a single wallet
      operationId: getWalletById
      parameters:
        - name: walletId
          in: path
          description: Id of the wallet to return
          required: true
          schema:
            $ref: "#/components/schemas/WalletId"
      responses:
        '200':
          description: Wallet retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
        '400':
          description: Malformed wallet id supplied
        '404':
          description: Wallet corresponding to the supplied wallet id not found
    delete:
      tags:
        - wallets
      summary: Delete a wallet by id
      description: Deletes a wallet by id
      operationId: deleteWallet
      parameters:
        - name: walletId
          in: path
          description: Wallet id to delete
          required: true
          schema:
            $ref: "#/components/schemas/WalletId"
      responses:
        '200':
          description: Wallet deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteWalletResponse'
        '400':
          description: Malformed wallet id supplied
        '404':
          description: Wallet corresponding to the supplied wallet id not found
components:
  schemas:
    WalletId:
      type: string
      format: uuid
    Wallet:
      type: object
      properties:
        paymentInstrumentId:
          type: string
    CreateWalletRequest:
      type: object
      properties:
        paymentInstrumentType:
          type: string
          enum: [ cards, paypal, bancomatpay ]
    CreateWalletResponse:
      type: object
      properties:
        walletItemId:
          type: string
        logoutURI:
          type: string
    UpdateWalletRequest:
      type: object
    UpdateWalletResponse:
      type: object
    DeleteWalletResponse:
      type: object
