openapi: 3.0.0
info:
  version: 0.0.1
  title: Pagopa eCommerce payment transactions service
  description: This microservice handles transaction's lifecycle and workflow.
  contact:
    name: pagoPA - Touchpoints team
tags:
  - name: transactions
    description: Api's for performing a transaction
    externalDocs:
      url: https://pagopa.atlassian.net/wiki/spaces/I/pages/611287199/-servizio+transactions+service
      description: Technical specifications
externalDocs:
  url: https://pagopa.atlassian.net/wiki/spaces/I/pages/492339720/pagoPA+eCommerce+Design+Review
  description: Design review
paths:
  /wallet:
    post:
      operationId: newWallet
      tags:
        - wallet
      description: Create a new walllet
      parameters:
        - in: header
          name: X-Client-Id
          required: true
          description: Transaction origin (populated by APIM policy)
          type: string
      summary: Make a new transaction
      requestBody:
        $ref: "#/components/requestBodies/NewWalletRequest"
      responses:
        '200':
          description: New transaction successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletResponse'
        '400':
          description: Formally invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /transactions/{transactionId}:
    get:
      tags:
        - wallet
      operationId: getTransactionInfo
      summary: Get wallet information
      description: Return information for the input specific wallet resource
      parameters:
        - in: path
          name: walletId
          schema:
            type: string
          required: true
          description: Wallet ID
      responses:
        '200':
          description: Transaction data successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionInfo"
        '400':
          description: Invalid transaction id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
        '404':
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
    delete:
      tags:
        - transactions
      operationId: requestTransactionUserCancellation
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction ID
      summary: Performs the cancellation of the transaction
      responses:
        '202':
          description: Transaction cancellation request successfully accepted
        '404':
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '409':
          description: Conflict on payment status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
components:
  schemas:
    NewWalletRequest:
      description: Request body for creating a new wallet
      type: object
      properties:
        name:
          type: string
        email:
          description: Email string format
          type: string
          pattern: (?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
          example : mario.rossi@gmail.it
      required:
        - name
        - email
    WalletResponse:
      type: object
      description: Wallet data returned when creating a new transaction
      properties:
        walletId:
          description: the wallet unique identifier
          schema:
            type: string
      required:
        - walletId
    ProblemJson:
      description: Body definition for error responses containing failure details
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: |-
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          $ref: "#/components/schemas/HttpStatusCode"
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    HttpStatusCode:
      type: integer
      format: int32
      description: |-
        The HTTP status code generated by the origin server for this occurrence
        of the problem.
      minimum: 100
      maximum: 600
      exclusiveMaximum: true
      example: 200
  requestBodies:
    NewWalletRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NewWalletRequest"
