apiVersion: v2
name: non-critical-wallet
description: Microservice that handles crud operations on wallet resources
type: application
version: 2.17.1
appVersion: 2.17.1
dependencies:
  - name: microservice-chart
    version: 9.0.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
