microservice-chart:
  namespace: "wallet"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopawalletservice
    tag: "0.0.1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weudev.wallet.internal.dev.platform.pagopa.it"
    path: /pagopa-wallet-service/(.*)
  serviceAccount:
    create: false
    annotations: { }
    name: ""
  podAnnotations: { }
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.25"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    MONGO_HOST: pagopa-d-weu-wallet-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-d-weu-wallet-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    WEB_LOGGING_LEVEL: "off"
    NPG_SERVICE_URI: "https://stg-ta.nexigroup.com/api/phoenix-0.0/psp/api/v1"
    NPG_SERVICE_READ_TIMEOUT: "10000"
    NPG_SERVICE_CONNECTION_TIMEOUT: "10000"
    # TODO: Fill
    WEBSITE_SITE_NAME: 'wallet-service' # required to show cloud role name in application insights
  envSecret:
  MONGO_PASSWORD: mongo-wallet-password
  NPG_SERVICE_API_KEY: npg-service-api-key
  keyvault:
    name: "pagopa-d-wallet-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: { }
  tolerations: [ ]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    deployment:
      image:
        tag: ""

