name: Check PR

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, labeled, unlabeled, reopened, edited ]


permissions:
  pull-requests: write


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  auto_assign:
    name: Auto Assign

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Assign Me
        # You may pin to the exact commit or the version.
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/auto_assign.yml'

  check_labels:
    name: Check Required Labels
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Verify PR Labels
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'breaking-change') && !contains(github.event.pull_request.labels.*.name, 'enhancement') && !contains(github.event.pull_request.labels.*.name, 'bug') && !contains(github.event.pull_request.labels.*.name, 'ignore-for-release') }}
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var comments = await github.rest.issues.listComments({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
            });
            for (const comment of comments.data) {
              if (comment.body.includes('This pull request does not contain a valid label')){
                github.rest.issues.deleteComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id
                })
              }
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This pull request does not contain a valid label. Please add one of the following labels: `[bug, enhancement, breaking-change, ignore-for-release]`'
            })
            core.setFailed('Missing required labels')


  check_format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Formatting
        id: format
        continue-on-error: true
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"

      - uses: actions/github-script@v6.3.3
        if: steps.format.outcome != 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context);
            var comments = await github.rest.issues.listComments({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
            });
            for (const comment of comments.data) {
              console.log(comment);
              if (comment.body.includes('Comment this PR with')){
                github.rest.issues.deleteComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id
                })
              }
            }
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Comment this PR with *update_code* to format the code. Consider to use pre-commit to format the code.'
            })
            core.setFailed('Format your code.')

  check_size:
    runs-on: ubuntu-latest
    name: Check Size
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Size
        uses: actions/github-script@v6.3.3
        env:
          IGNORED_FILES: openapi.json, openapi-node.json
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const additions = context.payload.pull_request.additions || 0
            const deletions = context.payload.pull_request.deletions || 0
            var changes = additions + deletions
            console.log('additions: '+additions+' + deletions: '+deletions+ ' = total changes: ' + changes);

            const { IGNORED_FILES } = process.env
            const ignored_files = IGNORED_FILES.trim().split(',').filter(word => word.length > 0);
            if (ignored_files.length > 0){
              var ignored = 0
              const execSync = require('child_process').execSync;
              for (const file of IGNORED_FILES.trim().split(',')) {
            
                const ignored_additions_str = execSync('git --no-pager  diff --numstat origin/main..origin/${{ github.head_ref}} | grep ' + file + ' | cut -f 1', { encoding: 'utf-8' })
                const ignored_deletions_str = execSync('git --no-pager  diff --numstat origin/main..origin/${{ github.head_ref}} | grep ' + file + ' | cut -f 2', { encoding: 'utf-8' })
            
                const ignored_additions = ignored_additions_str.split('\n').map(elem=> parseInt(elem || 0)).reduce(
                (accumulator, currentValue) => accumulator + currentValue,
                0);
                const ignored_deletions = ignored_deletions_str.split('\n').map(elem=> parseInt(elem || 0)).reduce(
                (accumulator, currentValue) => accumulator + currentValue,
                0);
            
                ignored += ignored_additions + ignored_deletions;
              }
              changes -= ignored
              console.log('ignored lines: ' + ignored + ' , consider changes: ' + changes);
            }
            
            if (changes < 200){
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['size/small']
              })
            
            
              var labels = await github.rest.issues.listLabelsOnIssue({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              });

              if (labels.data.find(label => label.name == 'size/large')){
                github.rest.issues.removeLabel({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: 'size/large'
                })
              }
            }

            if (changes > 400){
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['size/large']
              })
            
              var comments = await github.rest.issues.listComments({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              for (const comment of comments.data) {
                if (comment.body.includes('This PR exceeds the recommended size')){
                  github.rest.issues.deleteComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: comment.id
                  })
                }
              }

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'This PR exceeds the recommended size of 400 lines. Please make sure you are NOT addressing multiple issues with one PR. _Note this PR might be rejected due to its size._'
              })
            
              var labels = await github.rest.issues.listLabelsOnIssue({
                 issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              });

              if (labels.data.find(label => label.name == 'size/small')){
                github.rest.issues.removeLabel({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: 'size/small'
                })
              }
            
              core.setFailed('PR is too large: ' + changes + ' changes.')
            }


  build:
    name: Code Review
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #
      # Cache Gradle dependencies and Gradle Wrapper
      #
      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      #
      # Setup Gradle
      #
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build
  pr_scan:
    name: pr scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Build the Docker image
        run: docker build . --file ${{ env.DOCKERFILE }} --tag localbuild/testimage:latest
      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
        id: scan
        with:
          image: "localbuild/testimage:latest"
          fail-build: true
          severity-cutoff: "high"
      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
        if: always()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
