name: Code Review

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_KEY: "pagopa_pagopa-wallet-service"
  PROJECT_NAME: "pagopa-wallet-service"

permissions:
  id-token: write
  contents: read
  deployments: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-review:
    name: Code Review
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Setup JDK 21
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Cache SonarQube packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and Test
        run: |
          ./gradlew clean test jacocoTestReport

      - name: Sonar Analysis for Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
          -Dsonar.organization="pagopa" \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.projectKey=${{ env.PROJECT_KEY }} \
          -Dsonar.projectName=${{ env.PROJECT_NAME }} \
          -Dsonar.sources=src/main \
          -Dsonar.tests=src/test \
          -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
          -Dsonar.coverage.exclusions="**/config/*,**/*Mock*,**/model/**,**/entity/*,**/*Application*" \
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
          -Dsonar.pullrequest.branch=${{ github.head_ref }} \
          -Dsonar.pullrequest.base=${{ github.base_ref }}

      - name: Sonar Analysis for Main Branch
        if: ${{ github.event_name != 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
          -Dsonar.organization="pagopa" \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.projectKey=${{ env.PROJECT_KEY }} \
          -Dsonar.projectName=${{ env.PROJECT_NAME }} \
          -Dsonar.sources=src/main \
          -Dsonar.tests=src/test \
          -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
          -Dsonar.coverage.exclusions="**/config/*,**/*Mock*,**/model/**,**/entity/*,**/*Application*" \
          -Dsonar.branch.name=${{ github.ref_name }}